/** Homepage catalog only. Weather still loads on /station/[icao]. */

export type StaticCity = {
  city: string;
  icao: string;
};

export const CITIES: StaticCity[] = [
  { city: "Amsterdam", icao: "EHAM" },
  { city: "Ankara", icao: "LTAC" },
  { city: "Atlanta", icao: "KATL" },
  { city: "Austin", icao: "KAUS" },
  { city: "Beijing", icao: "ZBAA" },
  { city: "Buenos Aires", icao: "SAEZ" },
  { city: "Busan", icao: "RKPK" },
  { city: "Cape Town", icao: "FACT" },
  { city: "Chengdu", icao: "ZUUU" },
  { city: "Chicago", icao: "KORD" },
  { city: "Chongqing", icao: "ZUCK" },
  { city: "Dallas", icao: "KDAL" },
  { city: "Denver", icao: "KBKF" },
  { city: "Guangzhou", icao: "ZGGG" },
  { city: "Helsinki", icao: "EFHK" },
  { city: "Hong Kong", icao: "HKO" },
  { city: "Houston", icao: "KHOU" },
  { city: "Istanbul", icao: "LTFM" },
  { city: "Jeddah", icao: "OEJN" },
  { city: "Jinan", icao: "ZSJN" },
  { city: "Karachi", icao: "OPKC" },
  { city: "Kuala Lumpur", icao: "WMKK" },
  { city: "London", icao: "EGLC" },
  { city: "Los Angeles", icao: "KLAX" },
  { city: "Lucknow", icao: "VILK" },
  { city: "Madrid", icao: "LEMD" },
  { city: "Manila", icao: "RPLL" },
  { city: "Mexico City", icao: "MMMX" },
  { city: "Miami", icao: "KMIA" },
  { city: "Milan", icao: "LIMC" },
  { city: "Moscow", icao: "UUWW" },
  { city: "Munich", icao: "EDDM" },
  { city: "NYC", icao: "KLGA" },
  { city: "Panama City", icao: "MPMG" },
  { city: "Paris", icao: "LFPB" },
  { city: "Qingdao", icao: "ZSQD" },
  { city: "San Francisco", icao: "KSFO" },
  { city: "Sao Paulo", icao: "SBGR" },
  { city: "Seattle", icao: "KSEA" },
  { city: "Seoul (Incheon)", icao: "RKSI" },
  { city: "Shanghai", icao: "ZSPD" },
  { city: "Shenzhen", icao: "ZGSZ" },
  { city: "Singapore", icao: "WSSS" },
  { city: "Taipei", icao: "RCSS" },
  { city: "Tel Aviv", icao: "LLBG" },
  { city: "Tokyo", icao: "RJTT" },
  { city: "Toronto", icao: "CYYZ" },
  { city: "Warsaw", icao: "EPWA" },
  { city: "Wellington", icao: "NZWN" },
  { city: "Wuhan", icao: "ZHHH" },
  { city: "Zhengzhou", icao: "ZHCC" },
];
